import 'dart:io';
import 'image_layers.dart';
import 'models.dart';
import 'i18n.dart';

class AsciidocGenerator {
  Future<void> writeToFile(
    List<Package> packages,
    String outputPath, {
    String? documentName,
    LayerAnnotations? layers,
  }) async {
    final buf = StringBuffer();
    var title = documentName ??
        tr('Software Bill of Materials — Licences',
            'Software Bill of Materials — Licenses');
    if (layers?.isLayerDocument == true)
      title = '$title — ${layers!.layerLabel}';
    final sorted = List<Package>.from(packages)
      ..sort((a, b) => a.name.compareTo(b.name));

    buf.writeln('= $title');
    buf.writeln(':doctype: article');
    buf.writeln(':toc:');
    buf.writeln(':toclevels: 1');
    buf.writeln(':icons: font');
    buf.writeln();
    if (layers != null) {
      for (final line in layers.describe()) {
        buf.writeln('* ${_escText(line)}');
      }
      buf.writeln();
    }
    buf.writeln(layers != null
        ? '[cols="<1,<2,<1,<2,<1",options="header",stripes=odd]'
        : '[cols="<1,<2,<1,<2",options="header",stripes=odd]');
    buf.writeln('|===');
    buf.writeln(
        '| ${tr('Paquet', 'Package')} | Version | Architecture | ${tr('Licence', 'License')}'
        '${layers != null ? ' | ${layers.columnTitle}' : ''}');
    buf.writeln();

    for (final pkg in sorted) {
      final name = _esc(pkg.name);
      final version = _esc(pkg.fullVersion);
      final arch = _esc(pkg.arch);
      final license = _esc(
          pkg.license.isEmpty ? tr('(inconnue)', '(unknown)') : pkg.license);
      final layerCell =
          layers != null ? ' | ${_esc(layers.columnValue(pkg))}' : '';
      buf.writeln('| $name | $version | $arch | $license$layerCell');
    }

    buf.writeln('|===');
    if (layers != null && layers.removed.isNotEmpty) {
      buf.writeln();
      buf.writeln(
          tr('== Supprimés par cette couche', '== Removed by this layer'));
      buf.writeln();
      buf.writeln('[cols="<1,<2,<1",options="header",stripes=odd]');
      buf.writeln('|===');
      buf.writeln('| ${tr('Paquet', 'Package')} | Version | Architecture');
      buf.writeln();
      for (final pkg in layers.removed) {
        buf.writeln('| ${_esc(pkg.name)} | ${_esc(pkg.fullVersion)} '
            '| ${_esc(pkg.arch)}');
      }
      buf.writeln('|===');
    }
    buf.writeln();
    buf.writeln(tr(
        '_Généré par sbom_generator — ${packages.length} paquet(s)._',
        '_Generated by sbom_generator — ${packages.length} package(s)._'));

    await File(outputPath).writeAsString(buf.toString());
  }

  // Dans une cellule AsciiDoc inline, "|" en début de contenu est ambigu.
  // On échappe systématiquement pour éviter tout problème de rendu.
  String _esc(String s) => s.replaceAll('|', '\\|');

  // Texte courant (hors tableau) : neutralise les attributs `{…}` et les
  // macros de passage qu'une instruction de build pourrait contenir.
  String _escText(String s) =>
      s.replaceAll('{', '\\{').replaceAll('+++', '\\+++');
}
