import 'dart:io';
import 'image_layers.dart';
import 'models.dart';
import 'i18n.dart';

class MarkdownGenerator {
  Future<void> writeToFile(
    List<Package> packages,
    String outputPath, {
    String? documentName,
    LayerAnnotations? layers,
  }) async {
    final buf = StringBuffer();

    var title = documentName ??
        tr('Software Bill of Materials — Licences',
            'Software Bill of Materials — Licenses');
    if (layers?.isLayerDocument == true)
      title = '$title — ${layers!.layerLabel}';
    buf.writeln('# $title');
    buf.writeln();
    if (layers != null) {
      for (final line in layers.describe()) {
        buf.writeln('- ${_escape(line)}');
      }
      buf.writeln();
    }
    final extra = layers != null ? ' ${layers.columnTitle} |' : '';
    buf.writeln(
        '| ${tr('Paquet', 'Package')} | Version | ${tr('Architecture', 'Architecture')} | ${tr('Licence', 'License')} |$extra');
    buf.writeln('|--------|---------|--------------|---------|'
        '${layers != null ? '------|' : ''}');

    final sorted = List<Package>.from(packages)
      ..sort((a, b) => a.name.compareTo(b.name));

    for (final pkg in sorted) {
      final name = _escape(pkg.name);
      final version = _escape(pkg.fullVersion);
      final arch = _escape(pkg.arch);
      final license = _escape(
          pkg.license.isEmpty ? tr('(inconnue)', '(unknown)') : pkg.license);
      final layerCell =
          layers != null ? ' ${_escape(layers.columnValue(pkg))} |' : '';
      buf.writeln('| $name | $version | $arch | $license |$layerCell');
    }

    if (layers != null && layers.removed.isNotEmpty) {
      buf.writeln();
      buf.writeln(
          tr('## Supprimés par cette couche', '## Removed by this layer'));
      buf.writeln();
      buf.writeln('| ${tr('Paquet', 'Package')} | Version | Architecture |');
      buf.writeln('|--------|---------|--------------|');
      for (final pkg in layers.removed) {
        buf.writeln('| ${_escape(pkg.name)} | ${_escape(pkg.fullVersion)} '
            '| ${_escape(pkg.arch)} |');
      }
    }

    buf.writeln();
    buf.writeln(tr(
        '_Généré par sbom_generator — ${packages.length} paquet(s)._',
        '_Generated by sbom_generator — ${packages.length} package(s)._'));

    await File(outputPath).writeAsString(buf.toString());
  }

  String _escape(String s) => s.replaceAll('|', r'\|');
}
