// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get languageMenuTooltip => 'Interface language';

  @override
  String get languageSystem => 'System';

  @override
  String get languageFrench => 'Français';

  @override
  String get languageEnglish => 'English';

  @override
  String get commonCopy => 'Copy';

  @override
  String get commonClose => 'Close';

  @override
  String get commonStop => 'Stop';

  @override
  String get commonAnalyze => 'Analyze';

  @override
  String get commonBrowse => 'Browse';

  @override
  String commonPickFiltered(String filter) {
    return 'Filtered type ($filter)';
  }

  @override
  String get commonPickAllFiles => 'All files';

  @override
  String commonFileNotFound(String path) {
    return 'File not found: $path';
  }

  @override
  String get commonNone => '(none)';

  @override
  String get commonNoneFeminine => '(none)';

  @override
  String get commonPlatform => 'Platform';

  @override
  String get commonPlatformHint => 'linux/amd64, linux/arm64…';

  @override
  String get commonSbomFileHint => 'path/to/sbom.cdx.json';

  @override
  String get jsonViewEmpty => 'No JSON output.';

  @override
  String get jsonViewCopyTooltip => 'Copy JSON';

  @override
  String get jsonViewCopied => 'JSON copied';

  @override
  String get scanSourceSbom => 'SBOM file';

  @override
  String get scanSourceImage => 'Container image';

  @override
  String scanSourceImageHelp(String ociDirLine) {
    return 'Reference of an image to analyze directly, without\ngoing through an SBOM file:\n• Registry: nginx:latest, ghcr.io/org/app:tag\n• Archive: ./image.tar(.gz) (docker save)\n${ociDirLine}A private registry is resolved through the local\nDocker configuration (docker login), no dedicated field here.';
  }

  @override
  String get scanSourceImageHelpOciDir =>
      '• OCI layout directory: ./oci_dir/\n';

  @override
  String get scanSourcePickArchive => 'Choose an archive (.tar, .tar.gz, .tgz)';

  @override
  String get scanSourcePickOciDir => 'Choose an OCI layout directory';

  @override
  String get scanSourceMissingImage => 'Please enter an image to analyze.';

  @override
  String get scanSourceMissingSbom => 'Please select an SBOM file.';

  @override
  String get scanPickSbomTitle => 'Choose an SBOM file';

  @override
  String get scanPickImageArchiveTitle =>
      'Choose an image archive (docker save / OCI)';

  @override
  String scanUnreadableOutput(String tool, String error) {
    return 'Unreadable $tool output (invalid JSON): $error';
  }

  @override
  String scanUnreadableOutputShort(String tool) {
    return 'Unreadable $tool output: see the error message above';
  }

  @override
  String get scanNoVulnerabilities => 'No vulnerabilities found';

  @override
  String scanSummary(int count, String details) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count vulnerabilities: $details',
      one: '1 vulnerability: $details',
    );
    return '$_temp0';
  }

  @override
  String scanExportCsvDialog(String tool) {
    return 'Export $tool vulnerabilities';
  }

  @override
  String get layerScanCheckbox => 'Per layer';

  @override
  String get layerScanHelp =>
      'Attributes each vulnerability to the image layer that\nbrings the vulnerable package (per-layer SBOMs generated by\nsbom-generator --per-layer, with syft).\n• Attribution: a single scan of the image, each CVE\n  attributed to its package\'s origin layer — CVEs of the\n  final image only.\n• Each layer: the SBOM of each layer is scanned —\n  includes CVEs of a version replaced higher in the\n  stack (with the Rootfs computation).\n• Metadata / Rootfs: layer computation (--layer-mode).';

  @override
  String get layerScanAttribute => 'Attribution';

  @override
  String get layerScanAttributeTooltip =>
      'One scan of the image, CVEs attributed to the package\'s origin layer';

  @override
  String get layerScanEach => 'Each layer';

  @override
  String get layerScanEachTooltip => 'One scan per layer SBOM';

  @override
  String get layerModeMetadata => 'Metadata';

  @override
  String get layerModeMetadataTooltip =>
      'Origin layer reported by syft — additions';

  @override
  String get layerModeRootfs => 'Rootfs';

  @override
  String get layerModeRootfsTooltip =>
      'Rescan after each layer — additions, changes, removals';

  @override
  String get cliCommandButton => 'CLI command';

  @override
  String get cliCommandDialogTitle => 'Command line';

  @override
  String get cliCommandCopied => 'Command copied';

  @override
  String get cliCommandExecuted => 'Command run by the tab';

  @override
  String get cliCommandExecutedLayered =>
      'Commands run by the tab (per-layer analysis)';

  @override
  String get cliCommandEquivalent => 'sbom-generator scan equivalent';

  @override
  String cliCommandLayerDirNote(String dir) {
    return 'The per-layer SBOM set is generated in a temporary directory (here $dir).';
  }

  @override
  String get cliCommandImageNote =>
      'With --image, sbom-generator scans the generated CycloneDX SBOM (syft), not the image itself.';

  @override
  String cliCommandNotCarried(String options) {
    return 'Not transposable: $options.';
  }

  @override
  String get cliOptionPlatform => 'platform';

  @override
  String get vulnTableFilter => 'Filter:';

  @override
  String get vulnTableShowAll => 'Show all';

  @override
  String vulnTableKevChip(int count) {
    return 'CISA KEV ($count)';
  }

  @override
  String get vulnTableSearchHint => 'Package or CVE…';

  @override
  String get vulnTableEnrichOnline =>
      'Online enrichment on (CISA KEV / EPSS / poc-in-github) — click to go offline';

  @override
  String get vulnTableEnrichOffline =>
      'Offline enrichment (Grype + local cache only) — click to use the network again';

  @override
  String get vulnTableExportCsv => 'Export CSV';

  @override
  String get vulnTableExportPdf => 'Export to AsciiDoc + PDF';

  @override
  String vulnTableExportPdfDialog(String tool) {
    return 'Export the $tool report (AsciiDoc + PDF)';
  }

  @override
  String vulnTableExported(int count, String path) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count vulnerabilities exported → $path',
      one: '1 vulnerability exported → $path',
    );
    return '$_temp0';
  }

  @override
  String vulnTableExportedPdf(int count, String path, String pdf) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count vulnerabilities exported → $path and $pdf',
      one: '1 vulnerability exported → $path and $pdf',
    );
    return '$_temp0';
  }

  @override
  String vulnTableExportedPdfFailed(int count, String path, int code) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other:
          '$count vulnerabilities exported → $path (PDF conversion failed, code $code)',
      one:
          '1 vulnerability exported → $path (PDF conversion failed, code $code)',
    );
    return '$_temp0';
  }

  @override
  String vulnTableExportedNoPdf(int count, String path) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other:
          '$count vulnerabilities exported → $path (asciidoctor-pdf not found, no PDF)',
      one:
          '1 vulnerability exported → $path (asciidoctor-pdf not found, no PDF)',
    );
    return '$_temp0';
  }

  @override
  String get vulnTableColSeverity => 'SEVERITY';

  @override
  String get vulnTableColId => 'CVE / ID';

  @override
  String get vulnTableColPackage => 'PACKAGE';

  @override
  String get vulnTableColLayer => 'LAYER';

  @override
  String vulnTableUnattributed(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other:
          '$count vulnerabilities with no known layer (package missing from the image SBOM) — “?” column.',
      one:
          '1 vulnerability with no known layer (package missing from the image SBOM) — “?” column.',
    );
    return '$_temp0';
  }

  @override
  String get vulnTableEnrichPending =>
      'Online enrichment (CISA KEV / EPSS / PoC) in progress…';

  @override
  String vulnTableNoMatchSearch(String term) {
    return 'No results for \"$term\"';
  }

  @override
  String vulnTableNoMatchFilter(String filters) {
    return 'No results for $filters';
  }

  @override
  String vulnTableOccurrences(int count) {
    return 'This component appears in $count distinct places of the image/SBOM (e.g. a standalone library and a copy bundled in another package) — the same vulnerability was merged into a single row.';
  }

  @override
  String get vulnTableNoExploitSignal => 'no exploitation signal';

  @override
  String vulnTableKevTooltip(String added, String ransomware) {
    return 'CISA KEV — actively exploited in the wild$added$ransomware';
  }

  @override
  String vulnTableKevAdded(String date) {
    return ' (added on $date)';
  }

  @override
  String get vulnTableKevRansomware => ' · used by ransomware';

  @override
  String vulnTableEpssTooltip(int percentile) {
    return 'EPSS — probability of exploitation within 30 days (percentile $percentile)';
  }

  @override
  String vulnTablePocRepos(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count public PoC repositories listed',
      one: '1 public PoC repository listed',
    );
    return '$_temp0';
  }

  @override
  String vulnTablePocMaturity(String maturity) {
    return 'Exploit maturity: $maturity';
  }

  @override
  String vulnTableExploitabilityTooltip(String maturity) {
    return 'CVSS exploitability subscore (AV/AC/PR/UI)$maturity';
  }

  @override
  String vulnTableExploitabilityMaturity(String maturity) {
    return ' · maturity $maturity';
  }

  @override
  String get vulnTableAllLayers => 'All layers';

  @override
  String vulnTableLayerItem(int index, int count) {
    return 'Layer $index ($count)';
  }

  @override
  String get vulnTableFlatList => 'Flat list';

  @override
  String get vulnTableGroupByLayer => 'Group by layer';

  @override
  String get vulnTableLayerUnknownTooltip =>
      'Unknown layer (package missing from the image SBOM)';

  @override
  String get vulnTableLayerUnknown => 'Unknown layer';

  @override
  String vulnTableLayerLabel(int index) {
    return 'Layer $index';
  }

  @override
  String get dateFilterLabel => 'CVE date:';

  @override
  String get dateFilterPublished => 'Published';

  @override
  String get dateFilterModified => 'Modified';

  @override
  String get dateFilterLatest => 'Most recent';

  @override
  String get dateFilterAfterEmpty => 'After…';

  @override
  String dateFilterAfter(String date) {
    return 'After: $date';
  }

  @override
  String get dateFilterBeforeEmpty => 'Before…';

  @override
  String dateFilterBefore(String date) {
    return 'Before: $date';
  }

  @override
  String get dateFilterUndated => 'Undated';

  @override
  String get dateFilterPropagate => 'Apply to other tabs';

  @override
  String get grypePickConfigTitle => 'Choose grype.yaml';

  @override
  String get grypePickTemplateTitle => 'Choose a Grype template file';

  @override
  String grypeTabTable(int count) {
    return 'Table ($count)';
  }

  @override
  String get grypeTabJson => 'JSON';

  @override
  String get grypeTabTemplate => 'Template';

  @override
  String get grypeColType => 'TYPE';

  @override
  String get grypePlatformHelp =>
      'Optional. Forces the target platform on a\nmulti-architecture image, e.g. linux/arm64.\nLeave empty = automatic detection by\ngrype (the --platform linux box below does\nnot apply in image mode).';

  @override
  String get grypePlatformLinuxHelp =>
      'Sets the target platform to linux/amd64.\nEnable it if Grype does not detect\nthe image platform automatically.';

  @override
  String get grypeAddCpesHelp =>
      'Generates CPEs (Common Platform Enumeration)\nfor packages that have none.\nImproves the CVE match rate.';

  @override
  String get grypeByCveHelp =>
      'Groups results by CVE rather than by\npackage. Avoids duplicates when several\npackages are affected by the same CVE.';

  @override
  String get grypeDistroHelp =>
      'Target distribution for CVE evaluation.\nIf empty, Grype tries to detect it\nautomatically from the SBOM.';

  @override
  String get grypeFailOnHelp =>
      'Minimum severity for Grype to return\nexit code 1 (useful in CI/CD).\nIf empty, Grype always returns 0.';

  @override
  String get grypeOnlyFixedHelp =>
      'Only shows vulnerabilities for which\na fixed version is available.';

  @override
  String get grypeTemplateLabel => 'Template (-t)';

  @override
  String get grypeTemplateHelp =>
      'Go template to format Grype\'s output.\nE.g. ./grype_csv.tmpl for a CSV export.\nSee the Grype docs for the template syntax.';

  @override
  String get grypeConfigLabel => 'grype.yaml (optional)';

  @override
  String get grypeConfigHelp =>
      'Grype configuration file (YAML).\nLets you define exceptions, data sources,\nor customize the behavior.';

  @override
  String get grypeConfigHint => '/path/to/grype.yaml';

  @override
  String get grypeTemplateEmptyRun =>
      'Run the analysis to display the template output';

  @override
  String get grypeTemplateEmptyConfigure =>
      'Configure a template file (-t) to enable this view';

  @override
  String get grypeTemplateCopyTooltip => 'Copy the output';

  @override
  String get grypeTemplateCopied => 'Template output copied';

  @override
  String get grypeEmptyHint =>
      'Choose an SBOM file or a container image,\nthen run the Grype analysis';

  @override
  String get grypeRunning => 'Grype analysis in progress…';

  @override
  String grypeCliTemplateOutputNote(String file) {
    return 'Template output written to a temporary file (here $file).';
  }

  @override
  String get grypeCliTemplateNotLayered =>
      'The template (-t) is not applied in per-layer analysis.';

  @override
  String get grypeCliCpesByCveUnchecked =>
      'unchecking --add-cpes-if-none / --by-cve (always on)';

  @override
  String get layerScanStepPreparing => 'Preparing the layer SBOMs…';

  @override
  String get layerScanStepImage => 'Scanning the image…';

  @override
  String layerScanStepLayer(int index, int total) {
    return 'Layer $index/$total…';
  }

  @override
  String get scanSourcePackage => 'Package / archive';

  @override
  String get scanSourcePackageHint =>
      'path/to/app.rpm, release.tar.gz, app.jar…';

  @override
  String get scanSourcePackageHelp =>
      'Local package or archive (rpm, deb, tar/tgz, zip, jar/war/ear,\nwheel) analyzed directly: the SBOM is first generated by\nsbom-generator (--input … --depth N) then scanned.\nWith a depth > 0, the contained jars, packages and archives\n(e.g. the jars inside an RPM) are analyzed too.';

  @override
  String get scanPackageDepthLabel => 'Depth';

  @override
  String get scanPackageDepthHelp =>
      'Levels of nested objects to descend into:\n• 0: the object only\n• N: N levels (1 = jars/packages/archives contained in\n  the object, 2 = what those contain…)\n• Unlimited: every level (capped at 10)\nManifests found (package-lock.json, go.sum, pom.xml…)\nare analyzed. Extraction is size-bounded.';

  @override
  String get scanPackageDepthNone => '0 — object only';

  @override
  String get scanPackageDepthAll => 'Unlimited';

  @override
  String scanPackageDepthLevels(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count levels',
      one: '1 level',
    );
    return '$_temp0';
  }

  @override
  String get scanSourceMissingPackage =>
      'Please select a package or an archive.';

  @override
  String get scanPickPackageTitle => 'Choose a package or an archive';

  @override
  String get scanPackagePreparing => 'Generating the package SBOM…';

  @override
  String scanPackageFailed(String error) {
    return 'Could not generate the SBOM: $error';
  }

  @override
  String get cliCommandPackagePrepare =>
      'Package SBOM generation (preliminary step)';

  @override
  String get cliCommandPackageNote =>
      'The SBOM is generated in a temporary directory; each CVE is attributed to the object containing the vulnerable package (OBJET column) in the sbom-generator scan equivalent.';
}
