@TestOn('posix')
library;

import 'dart:io';
import 'package:sbom_generator/jar_parser.dart';
import 'package:test/test.dart';

Future<bool> _hasTool(String name, List<String> args) async {
  try {
    final r = await Process.run(name, args);
    return r.exitCode == 0;
  } on ProcessException {
    return false;
  }
}

void main() {
  late Directory tmp;
  late bool hasZipTools;

  setUpAll(() async {
    hasZipTools =
        await _hasTool('zip', ['-v']) && await _hasTool('unzip', ['-v']);
  });

  setUp(() => tmp = Directory.systemTemp.createTempSync('jar_test_'));
  tearDown(() => tmp.deleteSync(recursive: true));

  /// Construit un .jar réel (via `zip`) contenant un pom.properties Maven.
  Future<String> _buildJarWithPomProperties({
    required String groupId,
    required String artifactId,
    required String version,
    String jarName = 'lib.jar',
  }) async {
    final propsDir =
        Directory('${tmp.path}/META-INF/maven/$groupId/$artifactId')
          ..createSync(recursive: true);
    File('${propsDir.path}/pom.properties').writeAsStringSync(
        '#Generated by Maven\n'
        'groupId=$groupId\n'
        'artifactId=$artifactId\n'
        'version=$version\n');

    final jarPath = '${tmp.path}/$jarName';
    final result = await Process.run(
        'zip', ['-q', '-r', jarPath, 'META-INF'],
        workingDirectory: tmp.path);
    expect(result.exitCode, 0, reason: result.stderr.toString());
    return jarPath;
  }

  /// Construit un .jar réel (via `zip`) avec un META-INF/MANIFEST.MF donné,
  /// sans pom.properties — reproduit les jars réels sans métadonnées Maven.
  Future<String> _buildJarWithManifest(String manifest, String jarName) async {
    final metaDir = Directory('${tmp.path}/META-INF')..createSync();
    File('${metaDir.path}/MANIFEST.MF').writeAsStringSync(manifest);

    final jarPath = '${tmp.path}/$jarName';
    final result = await Process.run(
        'zip', ['-q', '-r', jarPath, 'META-INF'],
        workingDirectory: tmp.path);
    expect(result.exitCode, 0, reason: result.stderr.toString());
    return jarPath;
  }

  /// Construit un .jar réel embarquant PLUSIEURS pom.properties (le sien +
  /// une ou plusieurs dépendances relocalisées), comme un jar « shaded »/
  /// uber-jar réel (ex. netty-common qui embarque jctools-core).
  Future<String> _buildShadedJar({
    required String ownGroupId,
    required String ownArtifactId,
    required String ownVersion,
    required List<(String, String, String)> bundled,
    required String jarName,
  }) async {
    void writeProps(String groupId, String artifactId, String version) {
      final dir = Directory('${tmp.path}/META-INF/maven/$groupId/$artifactId')
        ..createSync(recursive: true);
      File('${dir.path}/pom.properties').writeAsStringSync(
          '#Generated by Maven\n'
          'groupId=$groupId\n'
          'artifactId=$artifactId\n'
          'version=$version\n');
    }

    writeProps(ownGroupId, ownArtifactId, ownVersion);
    for (final (groupId, artifactId, version) in bundled) {
      writeProps(groupId, artifactId, version);
    }

    final jarPath = '${tmp.path}/$jarName';
    final result = await Process.run(
        'zip', ['-q', '-r', jarPath, 'META-INF'],
        workingDirectory: tmp.path);
    expect(result.exitCode, 0, reason: result.stderr.toString());
    return jarPath;
  }

  group('JarParser.parseJarFile — jar « shaded »/uber-jar', () {
    test('retient sa propre identité plutôt qu\'une dépendance relocalisée',
        () async {
      if (!hasZipTools) {
        markTestSkipped('zip/unzip absents — test ignoré');
        return;
      }
      // Reproduit netty-common-4.1.100.Final.jar, qui embarque aussi le
      // pom.properties de org.jctools:jctools-core.
      final jarPath = await _buildShadedJar(
        ownGroupId: 'io.netty',
        ownArtifactId: 'netty-common',
        ownVersion: '4.1.100.Final',
        bundled: [('org.jctools', 'jctools-core', '3.1.0')],
        jarName: 'netty-common-4.1.100.Final.jar',
      );

      final pkg = await JarParser().parseJarFile(jarPath);
      expect(pkg, isNotNull);
      expect(pkg!.purl, 'pkg:maven/io.netty/netty-common@4.1.100.Final');
    });

    test('repli sur le nom de fichier si aucun pom.properties ne correspond',
        () async {
      if (!hasZipTools) {
        markTestSkipped('zip/unzip absents — test ignoré');
        return;
      }
      // Aucun des pom.properties embarqués ne correspond au nom du jar
      // lui-même : impossible de savoir lequel est le bon, on ne devine pas.
      final jarPath = await _buildShadedJar(
        ownGroupId: 'com.example',
        ownArtifactId: 'something-else',
        ownVersion: '9.9.9',
        bundled: [('org.other', 'other-lib', '1.0.0')],
        jarName: 'my-app-2.0.0.jar',
      );

      final pkg = await JarParser().parseJarFile(jarPath);
      expect(pkg, isNotNull);
      expect(pkg!.purl, 'pkg:maven/my-app/my-app@2.0.0');
    });
  });

  group('JarParser.parseJarFile — pom.properties', () {
    test('extrait groupId/artifactId/version depuis META-INF/maven', () async {
      if (!hasZipTools) {
        markTestSkipped('zip/unzip absents — test ignoré');
        return;
      }
      final jarPath = await _buildJarWithPomProperties(
        groupId: 'com.example',
        artifactId: 'my-lib',
        version: '1.2.3',
      );

      final pkg = await JarParser().parseJarFile(jarPath);
      expect(pkg, isNotNull);
      expect(pkg!.name, 'com.example:my-lib');
      expect(pkg.version, '1.2.3');
      expect(pkg.packageType, 'maven');
      expect(pkg.purl, 'pkg:maven/com.example/my-lib@1.2.3');
      expect(pkg.vendor, 'com.example');
    });
  });

  group('JarParser.parseJarFile — fallback nom de fichier', () {
    test('déduit les coordonnées du nom de fichier sans pom.properties',
        () async {
      final jarPath = '${tmp.path}/org.apache.commons.commons-lang3-3.14.0.jar';
      File(jarPath).writeAsBytesSync([]); // fichier vide, pas un vrai zip

      final pkg = await JarParser().parseJarFile(jarPath);
      expect(pkg, isNotNull);
      expect(pkg!.name, 'org.apache.commons:commons-lang3');
      expect(pkg.version, '3.14.0');
      expect(pkg.purl, 'pkg:maven/org.apache.commons/commons-lang3@3.14.0');
    });

    test('retourne null quand ni pom.properties ni convention de nom ne matchent',
        () async {
      final jarPath = '${tmp.path}/mystery.jar';
      File(jarPath).writeAsBytesSync([]);

      final pkg = await JarParser().parseJarFile(jarPath);
      expect(pkg, isNull);
    });

    test('utilise artifactId comme groupId quand rien d\'autre n\'est disponible',
        () async {
      // Fichier vide (pas un zip valide) : ni pom.properties ni manifeste
      // lisibles, et le nom ne suit pas la convention groupId.artifactId.
      final jarPath = '${tmp.path}/aopalliance-1.0.jar';
      File(jarPath).writeAsBytesSync([]);

      final pkg = await JarParser().parseJarFile(jarPath);
      expect(pkg, isNotNull);
      expect(pkg!.name, 'aopalliance:aopalliance');
      expect(pkg.version, '1.0');
      expect(pkg.purl, 'pkg:maven/aopalliance/aopalliance@1.0');
    });
  });

  group('JarParser.parseJarFile — repli sur META-INF/MANIFEST.MF', () {
    test('récupère le groupId via Bundle-SymbolicName (jar OSGi sans pom.properties)',
        () async {
      if (!hasZipTools) {
        markTestSkipped('zip/unzip absents — test ignoré');
        return;
      }
      final jarPath = await _buildJarWithManifest(
        'Manifest-Version: 1.0\n'
        'Bundle-SymbolicName: com.github.ben-manes.caffeine\n'
        'Bundle-Version: 2.9.3\n',
        'caffeine-2.9.3.jar',
      );

      final pkg = await JarParser().parseJarFile(jarPath);
      expect(pkg, isNotNull);
      expect(pkg!.purl, 'pkg:maven/com.github.ben-manes.caffeine/caffeine@2.9.3');
    });

    test('priorité Implementation-Vendor-Id > Implementation-Title', () async {
      if (!hasZipTools) {
        markTestSkipped('zip/unzip absents — test ignoré');
        return;
      }
      final jarPath = await _buildJarWithManifest(
        'Manifest-Version: 1.0\n'
        'Implementation-Title: org.apache.commons.httpclient\n'
        'Implementation-Vendor-Id: org.apache\n',
        'commons-httpclient-3.1.jar',
      );

      final pkg = await JarParser().parseJarFile(jarPath);
      expect(pkg, isNotNull);
      expect(pkg!.purl, 'pkg:maven/org.apache/commons-httpclient@3.1');
    });

    test('ignore une valeur de manifeste non conforme (casse, pas de point)',
        () async {
      if (!hasZipTools) {
        markTestSkipped('zip/unzip absents — test ignoré');
        return;
      }
      // Automatic-Module-Name contient une majuscule interne (baseEmpty) :
      // ce n'est pas un vrai nom de package Java, doit être rejeté.
      final jarPath = await _buildJarWithManifest(
        'Manifest-Version: 1.0\n'
        'Automatic-Module-Name: javafx.baseEmpty\n',
        'javafx-base-13.jar',
      );

      final pkg = await JarParser().parseJarFile(jarPath);
      expect(pkg, isNotNull);
      expect(pkg!.purl, 'pkg:maven/javafx-base/javafx-base@13');
    });

    test('prend la première occurrence d\'une clé répétée (manifeste multi-sections)',
        () async {
      if (!hasZipTools) {
        markTestSkipped('zip/unzip absents — test ignoré');
        return;
      }
      final jarPath = await _buildJarWithManifest(
        'Manifest-Version: 1.0\n'
        'Implementation-Title: org.apache.xmlcommons.version\n'
        '\n'
        'Name: org/xml/sax/\n'
        'Implementation-Title: org.xml.sax\n',
        'xml-apis-1.3.04.jar',
      );

      final pkg = await JarParser().parseJarFile(jarPath);
      expect(pkg, isNotNull);
      expect(pkg!.purl, 'pkg:maven/org.apache.xmlcommons.version/xml-apis@1.3.04');
    });
  });
}
