@TestOn('posix')
library;

import 'dart:io';
import 'package:sbom_generator/jar_parser.dart';
import 'package:test/test.dart';

Future<bool> _hasTool(String name, List<String> args) async {
  try {
    final r = await Process.run(name, args);
    return r.exitCode == 0;
  } on ProcessException {
    return false;
  }
}

void main() {
  late Directory tmp;
  late bool hasZipTools;

  setUpAll(() async {
    hasZipTools =
        await _hasTool('zip', ['-v']) && await _hasTool('unzip', ['-v']);
  });

  setUp(() => tmp = Directory.systemTemp.createTempSync('jar_test_'));
  tearDown(() => tmp.deleteSync(recursive: true));

  /// Construit un .jar réel (via `zip`) contenant un pom.properties Maven.
  Future<String> _buildJarWithPomProperties({
    required String groupId,
    required String artifactId,
    required String version,
    String jarName = 'lib.jar',
  }) async {
    final propsDir =
        Directory('${tmp.path}/META-INF/maven/$groupId/$artifactId')
          ..createSync(recursive: true);
    File('${propsDir.path}/pom.properties').writeAsStringSync(
        '#Generated by Maven\n'
        'groupId=$groupId\n'
        'artifactId=$artifactId\n'
        'version=$version\n');

    final jarPath = '${tmp.path}/$jarName';
    final result = await Process.run(
        'zip', ['-q', '-r', jarPath, 'META-INF'],
        workingDirectory: tmp.path);
    expect(result.exitCode, 0, reason: result.stderr.toString());
    return jarPath;
  }

  group('JarParser.parseJarFile — pom.properties', () {
    test('extrait groupId/artifactId/version depuis META-INF/maven', () async {
      if (!hasZipTools) {
        markTestSkipped('zip/unzip absents — test ignoré');
        return;
      }
      final jarPath = await _buildJarWithPomProperties(
        groupId: 'com.example',
        artifactId: 'my-lib',
        version: '1.2.3',
      );

      final pkg = await JarParser().parseJarFile(jarPath);
      expect(pkg, isNotNull);
      expect(pkg!.name, 'com.example:my-lib');
      expect(pkg.version, '1.2.3');
      expect(pkg.packageType, 'maven');
      expect(pkg.purl, 'pkg:maven/com.example/my-lib@1.2.3');
      expect(pkg.vendor, 'com.example');
    });
  });

  group('JarParser.parseJarFile — fallback nom de fichier', () {
    test('déduit les coordonnées du nom de fichier sans pom.properties',
        () async {
      final jarPath = '${tmp.path}/org.apache.commons.commons-lang3-3.14.0.jar';
      File(jarPath).writeAsBytesSync([]); // fichier vide, pas un vrai zip

      final pkg = await JarParser().parseJarFile(jarPath);
      expect(pkg, isNotNull);
      expect(pkg!.name, 'org.apache.commons:commons-lang3');
      expect(pkg.version, '3.14.0');
      expect(pkg.purl, 'pkg:maven/org.apache.commons/commons-lang3@3.14.0');
    });

    test('retourne null quand ni pom.properties ni convention de nom ne matchent',
        () async {
      final jarPath = '${tmp.path}/mystery.jar';
      File(jarPath).writeAsBytesSync([]);

      final pkg = await JarParser().parseJarFile(jarPath);
      expect(pkg, isNull);
    });
  });
}
