import 'dart:io';
import 'package:sbom_generator/pubspec_parser.dart';
import 'package:test/test.dart';

void main() {
  late Directory tmp;
  setUp(() => tmp = Directory.systemTemp.createTempSync('pubspec_test_'));
  tearDown(() => tmp.deleteSync(recursive: true));

  File _write(String name, String content) {
    final f = File('${tmp.path}/$name');
    f.writeAsStringSync(content);
    return f;
  }

  final parser = PubspecParser();

  group('PubspecParser.parsePubspecLock', () {
    test('extrait les paquets hosted avec version, sha256 et PURL pkg:pub', () {
      final f = _write('pubspec.lock', '''
# Generated by pub
packages:
  archive:
    dependency: transitive
    description:
      name: archive
      sha256: "abc123def"
      url: "https://pub.dev"
    source: hosted
    version: "3.4.10"
  args:
    dependency: "direct main"
    description:
      name: args
      sha256: deadbeef
      url: "https://pub.dev"
    source: hosted
    version: "2.4.2"
sdks:
  dart: ">=3.0.0 <4.0.0"
''');
      final pkgs = parser.parsePubspecLock(f.path);
      expect(pkgs, hasLength(2));

      final args = pkgs.firstWhere((p) => p.name == 'args');
      expect(args.version, '2.4.2');
      expect(args.packageType, 'pub');
      expect(args.purl, 'pkg:pub/args@2.4.2');
      expect(args.sha256Header, 'deadbeef');
      expect(args.url, 'https://pub.dev/packages/args');

      final archive = pkgs.firstWhere((p) => p.name == 'archive');
      expect(archive.sha256Header, 'abc123def');
    });

    test('exclut les dépendances "direct dev" mais garde les transitives', () {
      final f = _write('pubspec.lock', '''
packages:
  test:
    dependency: "direct dev"
    description:
      name: test
      sha256: "x"
      url: "https://pub.dev"
    source: hosted
    version: "1.25.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      sha256: "y"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
''');
      final pkgs = parser.parsePubspecLock(f.path);
      final names = pkgs.map((p) => p.name).toSet();
      expect(names, isNot(contains('test')));
      expect(names, contains('boolean_selector'));
    });

    test('gère les sources git, path et sdk', () {
      final f = _write('pubspec.lock', '''
packages:
  my_git_dep:
    dependency: "direct main"
    description:
      path: "."
      ref: main
      resolved-ref: "0123456789abcdef"
      url: "https://github.com/acme/my_git_dep.git"
    source: git
    version: "1.0.0"
  my_local_dep:
    dependency: "direct main"
    description:
      path: "../my_local_dep"
      relative: true
    source: path
    version: "0.0.1"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
''');
      final pkgs = parser.parsePubspecLock(f.path);
      expect(pkgs.map((p) => p.name).toSet(),
          {'my_git_dep', 'my_local_dep', 'flutter'});

      final git = pkgs.firstWhere((p) => p.name == 'my_git_dep');
      expect(git.url, 'https://github.com/acme/my_git_dep.git');
      expect(git.purl, 'pkg:pub/my_git_dep@1.0.0');

      final local = pkgs.firstWhere((p) => p.name == 'my_local_dep');
      expect(local.url, '');

      final sdk = pkgs.firstWhere((p) => p.name == 'flutter');
      expect(sdk.purl, 'pkg:pub/flutter@0.0.0');
    });

    test('registre hébergé personnalisé → homepage sur ce registre', () {
      final f = _write('pubspec.lock', '''
packages:
  internal_lib:
    dependency: "direct main"
    description:
      name: internal_lib
      sha256: "z"
      url: "https://pub.acme.internal"
    source: hosted
    version: "4.2.0"
''');
      final pkgs = parser.parsePubspecLock(f.path);
      expect(pkgs.single.url, 'https://pub.acme.internal/packages/internal_lib');
    });

    test('fichier absent → liste vide', () {
      expect(parser.parsePubspecLock('${tmp.path}/nope.lock'), isEmpty);
    });
  });

  group('PubspecParser.parsePubspecYaml', () {
    test('ne lit que dependencies:, pas dev_dependencies:', () {
      final f = _write('pubspec.yaml', '''
name: my_app
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  http: '>=0.13.0 <2.0.0'
  collection: any
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.25.0
  lints: ^3.0.0
''');
      final pkgs = parser.parsePubspecYaml(f.path);
      final byName = {for (final p in pkgs) p.name: p};
      expect(byName.keys, containsAll(['args', 'http', 'collection', 'flutter']));
      expect(byName.keys, isNot(contains('test')));
      expect(byName.keys, isNot(contains('lints')));

      expect(byName['args']!.version, '2.4.2');
      expect(byName['args']!.purl, 'pkg:pub/args@2.4.2');
      expect(byName['http']!.version, ''); // range → pas de version unique
      expect(byName['collection']!.version, '');
      expect(byName['flutter']!.version, '');
    });

    test('fichier absent → liste vide', () {
      expect(parser.parsePubspecYaml('${tmp.path}/nope.yaml'), isEmpty);
    });
  });
}
