/// Integration test exercising the real CLI on a `pubspec.lock` passed
/// directly to --input, and on a directory containing both `pubspec.lock`
/// and `pubspec.yaml` (the lock must win, no duplicate components).
@TestOn('posix')
library;

import 'dart:convert';
import 'dart:io';
import 'package:test/test.dart';

void main() {
  late Directory tmp;
  setUp(() => tmp = Directory.systemTemp.createTempSync('pubspec_input_test_'));
  tearDown(() => tmp.deleteSync(recursive: true));

  const lock = '''
# Generated by pub
packages:
  args:
    dependency: "direct main"
    description:
      name: args
      sha256: "abc"
      url: "https://pub.dev"
    source: hosted
    version: "2.7.0"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: "def"
      url: "https://pub.dev"
    source: hosted
    version: "1.16.0"
  lints:
    dependency: "direct dev"
    description:
      name: lints
      sha256: "ghi"
      url: "https://pub.dev"
    source: hosted
    version: "3.0.0"
''';

  Future<Set<String>> _run(List<String> extraArgs) async {
    final outPath = '${tmp.path}/out.cdx.json';
    final result = await Process.run(
      'dart',
      [
        'run',
        'bin/sbom_generator.dart',
        ...extraArgs,
        '-o',
        outPath,
      ],
      workingDirectory: Directory.current.path,
    );
    expect(result.exitCode, 0, reason: '${result.stdout}\n${result.stderr}');
    final doc =
        jsonDecode(await File(outPath).readAsString()) as Map<String, dynamic>;
    return (doc['components'] as List)
        .map((c) => (c as Map)['purl'] as String)
        .toSet();
  }

  test('--input pubspec.lock direct : dev exclu, PURL pkg:pub', () async {
    final f = File('${tmp.path}/pubspec.lock')..writeAsStringSync(lock);
    final purls = await _run(['--input', f.path]);
    expect(purls, contains('pkg:pub/args@2.7.0'));
    expect(purls, contains('pkg:pub/meta@1.16.0'));
    expect(purls.any((p) => p.startsWith('pkg:pub/lints')), isFalse);
  }, timeout: const Timeout(Duration(seconds: 60)));

  test('--input <dossier> : pubspec.lock prime sur pubspec.yaml', () async {
    Directory('${tmp.path}/app').createSync();
    File('${tmp.path}/app/pubspec.lock').writeAsStringSync(lock);
    File('${tmp.path}/app/pubspec.yaml').writeAsStringSync('''
name: app
dependencies:
  args: ^2.7.0
''');
    final purls = await _run(['--input', '${tmp.path}/app']);
    // args ne doit apparaître qu'avec sa version résolue (issue du lock)
    expect(purls.where((p) => p.startsWith('pkg:pub/args')).toList(),
        ['pkg:pub/args@2.7.0']);
  }, timeout: const Timeout(Duration(seconds: 60)));
}
